apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: airflow
  namespace: kube-system
spec:
  chart: airflow
  version: 1.13.2
  repo: https://airflow.apache.org
  targetNamespace: airflow
  valuesContent: |
    executor: KubernetesExecutor
