apiVersion: v1
kind: Namespace
metadata:
  name: authelia
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: authelia
  namespace: kube-system
spec:
  chart: authelia
  version: 0.9.4
  repo: https://charts.authelia.com
  targetNamespace: authelia
