apiVersion: v1
kind: Namespace
metadata:
  name: bind
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: bind
  namespace: kube-system
spec:
  chart: bind9
  version: 1.0.1
  repo: https://nicholaswilde.github.io/helm-charts
  targetNamespace: bind
