apiVersion: v1
kind: Namespace
metadata:
  name: clickhouse
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: clickhouse
  namespace: kube-system
spec:
  chart: clickhouse
  version: 6.0.0
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: clickhouse
  valuesContent: |
    shards: 1
    replicaCount: 1
