apiVersion: v1
kind: Namespace
metadata:
  name: coqui-tts
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: coqui-tts
  namespace: kube-system
spec:
  chart: coqui
  version: 1.0.0
  repo: https://cowboysysop.github.io/charts
  targetNamespace: coqui-tts
