apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: keycloak
  namespace: kube-system
spec:
  chart: keycloak
  version: 19.3.2
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: keycloak
  valuesContent: |
    auth:
      adminUser: admin
