apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: kube-system
spec:
  chart: loki
  version: 6.24.0
  repo: https://grafana.github.io/helm-charts
  targetNamespace: loki
  valuesContent: |
    deploymentMode: SingleBinary
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
    singleBinary:
      replicas: 1
