apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mongodb
  namespace: kube-system
spec:
  chart: mongodb
  version: 14.7.2
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: mongodb
  valuesContent: |
    architecture: standalone
