apiVersion: v1
kind: Namespace
metadata:
  name: neo4j
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: neo4j
  namespace: kube-system
spec:
  chart: neo4j
  version: 5.17.0
  repo: https://helm.neo4j.com/neo4j
  targetNamespace: neo4j
  valuesContent: |
    neo4j:
      edition: community
