apiVersion: v1
kind: Namespace
metadata:
  name: opensearch
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: opensearch
  namespace: kube-system
spec:
  chart: opensearch
  version: 2.17.1
  repo: https://opensearch-project.github.io/helm-charts
  targetNamespace: opensearch
  valuesContent: |
    singleNode: true
