apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-community-prometheus-ns
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-community-prometheus
  namespace: kube-system
spec:
  chart: prometheus
  version: 29.3.0
  repo: https://prometheus-community.github.io/helm-charts
  targetNamespace: prometheus-community-prometheus-ns
  valuesContent: |
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    server:
      persistentVolume:
        enabled: false
