apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rabbitmq
  namespace: kube-system
spec:
  chart: rabbitmq
  version: 12.5.0
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: rabbitmq
  valuesContent: |
    replicaCount: 1
