apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: kube-system
spec:
  chart: redis
  version: 19.5.5
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: redis
  valuesContent: |
    architecture: standalone
