apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: spark
  namespace: kube-system
spec:
  chart: spark
  version: 8.4.0
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: spark
  valuesContent: |
    worker:
      replicaCount: 2
