apiVersion: v1
kind: Namespace
metadata:
  name: superset
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: superset
  namespace: kube-system
spec:
  chart: superset
  version: 0.12.9
  repo: https://apache.github.io/superset
  targetNamespace: superset
